import { useEffect, useState, type ReactNode } from "react";
import { changes, checks, context, daemon, evidence, memory, projects, session, tasks, terminal } from "../mocks/demo";
import type { SessionMode } from "../types/domain";

type View = "home" | "session" | "settings";
type Tool = "Changes" | "Plan" | "Terminal" | "Verification" | "Context" | "Memory" | "Evidence" | "Security" | "Browser";
const recents = ["Fix authentication flow", "Refactor provider router", "Design memory system", "Add retry to tool calls", "Improve error handling", "Optimize context loading", "Add tests for task engine"];
const Icon = ({ children }: { children: string }) => <span className="icon" aria-hidden="true">{children}</span>;

function Logo() { return <div className="logo"><span>✦</span><strong>AgentCode</strong></div>; }
function Sidebar({ view, collapsed, onNew, onSettings, onSession, toggle }: { view: View; collapsed: boolean; onNew(): void; onSettings(): void; onSession(): void; toggle(): void }) { return <aside className={`sidebar ${collapsed ? "collapsed" : ""}`}><Logo /><button className="new-task" onClick={onNew}><Icon>＋</Icon><span>New Task</span><kbd>⌘ N</kbd></button><nav><p>Projects</p>{projects.map((p, i) => <button className={`nav-item ${i === 0 ? "selected" : ""}`} key={p.id}><b>{p.color}</b><span>{p.name}</span>{i === 0 && <i>⌄</i>}</button>)}<button className="add"><Icon>＋</Icon><span>Add Project</span></button><p>Recent</p>{recents.map((name, i) => <button className={`recent ${i === 0 && view === "session" ? "selected" : ""}`} key={name} onClick={onSession}><Icon>▱</Icon><span>{name}</span></button>)}</nav><div className="sidebar-foot"><button className={`nav-item ${view === "settings" ? "selected" : ""}`} onClick={onSettings}><Icon>⚙</Icon><span>Settings</span></button><div className="daemon"><span className="pulse"/> <span>Agent Daemon</span><small>Running</small></div><button className="collapse" aria-label="Toggle sidebar" onClick={toggle}>‹</button></div></aside> }
function Composer({ home, onSend }: { home?: boolean; onSend(): void }) { const [value, setValue] = useState(""); return <div className={`composer ${home ? "home-composer" : ""}`}><textarea value={value} onChange={(e) => setValue(e.target.value)} placeholder={home ? "Describe your task..." : "Ask the agent anything..."} aria-label="Message the agent" /><div className="composer-bar">{home ? <><button><Icon>▣</Icon> AgentCode⌄</button><div className="mode-mini"><span>Agent</span><span>Discuss</span><span>Design</span></div></> : <><button>@ Context</button><button>＋ Add</button></>}<span className="grow"/><button>Auto⌄</button><button className="send" onClick={onSend} aria-label="Send message">↑</button></div></div> }
function Home({ onSend }: { onSend(): void }) { return <main className="home"><div className="home-center"><div className="hero-mark">✦</div><h1>What would you like to build?</h1><p>Turn your ideas into working code with AgentCode.</p><Composer home onSend={onSend}/><div className="suggestions">{["Fix authentication flow", "Refactor provider router", "Design a memory system", "Add tests for retry logic"].map(x => <button key={x}>{x}</button>)}</div></div></main> }
function ModeTabs({ mode, setMode }: { mode: SessionMode; setMode(mode: SessionMode): void }) { return <div className="mode-tabs" role="tablist">{(["agent", "discuss", "design"] as SessionMode[]).map(x => <button role="tab" aria-selected={mode === x} className={mode === x ? "active" : ""} onClick={() => setMode(x)} key={x}>{x[0].toUpperCase() + x.slice(1)}</button>)}</div> }
function AgentConversation({ mode }: { mode: SessionMode }) { if (mode === "discuss") return <div className="conversation"><article className="message user"><div className="avatar">A</div><div><b>You</b><p>Can you explain how the provider router works?</p></div></article><article className="message agent"><div className="agent-mark">✦</div><div><b>Agent</b><p>The provider router selects a capable healthy route for the request, then applies cost and fallback policy. It keeps provider concerns behind one boundary so the rest of the runtime asks for a model capability rather than a vendor.</p><button className="file-chip">▣ src/router/provider.ts</button></div></article></div>;
if (mode === "design") return <div className="conversation"><article className="message user"><div className="avatar">A</div><div><b>You</b><p>I want to design a better memory system for this project.</p></div></article><article className="message agent"><div className="agent-mark">✦</div><div><b>Agent</b><p>Let’s start with retrieval boundaries, freshness, and how decisions remain traceable to their sources.</p><div className="decision"><b>Decision summary</b><p>Use typed facts with freshness and evidence links, keeping generated context non-authoritative.</p></div></div></article></div>;
return <div className="conversation"><article className="message user"><div className="avatar">A</div><div><b>You</b><p>Users are getting logged out randomly. Investigate and fix.</p></div><time>10:42 AM</time></article><article className="message agent"><div className="agent-mark">✦</div><div className="message-body"><div className="message-head"><b>Agent</b><span className="status working">● Working</span></div><p>I’ll investigate the auth flow and session handling to find the root cause.</p><ol className="activity">{tasks.map(task => <li className={task.state} key={task.id}><span>{task.state === "done" ? "✓" : task.state === "in_progress" ? "◉" : "○"}</span><div>{task.title}{task.detail && <small>↳ {task.detail}</small>}</div></li>)}</ol><details className="tool" open><summary><span>✦</span> Tool Call: Read <em>src/middleware/auth.ts</em><i>✓</i></summary><pre>{`import { verifyToken, refresh } from '@/lib/auth';\nimport { NextResponse } from 'next/server';\n\nexport async function middleware(req: NextRequest) {\n  const token = req.cookies.get('session')?.value;\n  if (!token) return NextResponse.redirect('/login');\n}`}</pre></details><div className="decision"><b>Decision summary</b><p>Session refresh appears to fail when the refresh token expires.</p></div></div><time>10:42 AM</time></article></div> }
function RightPanel({ tool, setTool, open }: { tool: Tool; setTool(x: Tool): void; open: boolean }) { if (!open) return null; const primary: Tool[] = ["Changes", "Plan", "Terminal", "Verification", "Context"]; const extra: Tool[] = ["Browser", "Security", "Memory", "Evidence"]; let content: ReactNode;
if (tool === "Changes") content = <><div className="panel-summary"><b>3 files changed</b><span><strong>+241</strong> <i>−38</i></span></div>{changes.files.map((file, i) => <div className="changed-file" key={file.path}><div><b>▣ {file.path}</b><span><strong>+{file.additions}</strong> <i>−{file.deletions}</i></span></div>{i === 0 && <pre className="diff">{file.diff}</pre>}</div>)}<div className="panel-note"><b>Summary</b>{changes.summary.map(x => <p key={x}>{x}</p>)}<strong className="safe">◉ Safe change</strong></div></>;
else if (tool === "Plan") content = <ol className="panel-plan">{tasks.map(t => <li className={t.state} key={t.id}>{t.state === "done" ? "✓" : t.state === "in_progress" ? "◉" : "○"} {t.title}</li>)}</ol>;
else if (tool === "Terminal") content = <pre className="terminal">{terminal.join("\n")}</pre>;
else if (tool === "Verification") content = <div className="verify">{checks.map(c => <div key={c.name}><span>✓</span><b>{c.name}</b><small>{c.detail}</small></div>)}</div>;
else if (tool === "Context") content = <div className="context">{context.map(c => <div key={c.label}><small>{c.label}</small><b>{c.value}</b></div>)}</div>;
else if (tool === "Memory") content = <><input className="search" placeholder="Search memory..."/>{memory.map(m => <div className="memory" key={m.id}><b>{m.statement}</b><p>{m.type} · {m.freshness}</p><small>{m.source} · {m.date}</small></div>)}</>;
else if (tool === "Evidence") content = <div className="evidence">{evidence.map(e => <div key={e.id}><span>▱</span><b>{e.label}</b><small>{e.count}</small></div>)}</div>;
else if (tool === "Security") content = <><p className="muted">Mock display only — no scanners have been run.</p>{["Gitleaks — Passed", "Semgrep — Available", "Trivy — Available", "OSV — Available", "Checkov — Unavailable", "ZAP — Available"].map(x => <div className="scanner" key={x}>{x}</div>)}</>;
else content = <div className="browser"><b>Browser evidence</b><p>Backend-generated browser evidence will appear here when connected.</p><label>URL</label><input value="http://localhost:3000/login" readOnly/><p>Console issues · Network failures · Accessibility</p></div>;
return <aside className="right-panel"><div className="tool-tabs">{primary.map(x => <button className={tool === x ? "active" : ""} onClick={() => setTool(x)} key={x}>{x}</button>)}<button className={extra.includes(tool) ? "active" : ""} onClick={() => setTool(tool === "Memory" ? "Evidence" : "Memory")}>More⌄</button></div>{extra.includes(tool) && <div className="tool-subtabs">{extra.map(x => <button className={tool === x ? "active" : ""} onClick={() => setTool(x)} key={x}>{x}</button>)}</div>}<section className="panel-content">{content}</section></aside> }
function Workspace({ onSettings }: { onSettings(): void }) { const [mode, setMode] = useState<SessionMode>("agent"); const [tool, setTool] = useState<Tool>("Changes"); const [rightOpen, setRightOpen] = useState(true); return <main className="workspace"><header className="topbar"><div><h2>{session.title}</h2><span className="branch">⌘ {session.branch}</span></div><ModeTabs mode={mode} setMode={setMode}/><div className="top-actions"><button>Auto⌄</button><span className="online">●</span><button onClick={() => setRightOpen(!rightOpen)} aria-label="Toggle context panel">⇥</button><button onClick={onSettings}>⚙</button></div></header><div className={`workspace-body ${rightOpen ? "with-panel" : ""}`}><section className="session"><AgentConversation mode={mode}/><Composer onSend={() => undefined}/></section><RightPanel tool={tool} setTool={setTool} open={rightOpen}/></div></main> }
function Settings() { const [active, setActive] = useState("Providers & Models"); const nav = ["Providers & Models", "Tools", "Security Scanners", "Memory", "Daemon", "Autonomy Defaults", "Appearance"]; return <main className="settings"><header><h2>Settings</h2><input className="search" placeholder="Search settings..."/></header><div className="settings-body"><nav>{nav.map(x => <button className={active === x ? "active" : ""} onClick={() => setActive(x)} key={x}>{x}</button>)}</nav><section className="settings-content"><h3>{active}</h3>{active === "Providers & Models" ? <><label>Model Routing<select><option>Auto</option></select></label><label>Preferred model<select><option>GPT-5.1 (Latest)</option></select></label><label>Backup model<select><option>Auto fallback</option></select></label><h4>Provider Priority</h4>{["OpenAI", "Anthropic", "Google / Gemini", "Ollama", "LM Studio"].map((x,i) => <div className="setting-row" key={x}><b>{x}</b><span className={i < 2 ? "connected" : "unavailable"}>{i < 2 ? "Connected" : i === 2 ? "Disconnected" : "Unavailable"}</span><button className="switch" aria-label={`${x} enabled`} /></div>)}</> : active === "Daemon" ? <>{[["Status", "Running"], ["Instance ID", daemon.instanceId], ["Uptime", daemon.uptime], ["Socket", daemon.socket], ["Database", daemon.database], ["Recovery state", "Healthy"]].map(([a,b]) => <div className="setting-row" key={a}><b>{a}</b><span>{b}</span></div>)}<button className="secondary">Reconnect</button><button className="secondary">Restart daemon</button></> : <><p className="muted">This setting surface is ready for a later daemon adapter.</p>{active === "Memory" && <><div className="setting-row"><b>Embedding model</b><span>all-MiniLM-L6-v2</span></div><div className="setting-row"><b>Dimension</b><span>384</span></div><div className="setting-row"><b>Status</b><span className="connected">Ready</span></div></>}{active === "Appearance" && <><div className="setting-row"><b>Theme</b><span>Dark</span></div><div className="setting-row"><b>Accent</b><span>Indigo</span></div></>}</>}</section></div></main> }
function CommandPalette({ close, open }: { close(): void; open: boolean }) { if (!open) return null; return <div className="palette-backdrop" onMouseDown={close}><div className="palette" onMouseDown={e => e.stopPropagation()}><input autoFocus placeholder="Search commands..."/><p>New Task <kbd>⌘ N</kbd></p><p>Open recent session</p><p>Switch project</p><p>Agent mode</p><p>Discuss mode</p><p>Design mode</p><p>Open Changes</p><p>Open Terminal <kbd>⌘ J</kbd></p><p>Open Verification</p><p>Open Settings <kbd>⌘ ,</kbd></p></div></div> }
export function App() { const [view, setView] = useState<View>("home"); const [collapsed, setCollapsed] = useState(false); const [palette, setPalette] = useState(false); useEffect(() => { const listener = (e: KeyboardEvent) => { if (e.metaKey && e.key.toLowerCase() === "k") { e.preventDefault(); setPalette(true); } if (e.metaKey && e.key.toLowerCase() === "n") { e.preventDefault(); setView("home"); } if (e.metaKey && e.key.toLowerCase() === "b") { e.preventDefault(); setCollapsed(x => !x); } if (e.metaKey && e.key === ",") { e.preventDefault(); setView("settings"); } }; window.addEventListener("keydown", listener); return () => window.removeEventListener("keydown", listener); }, []); return <div className="app-shell"><Sidebar view={view} collapsed={collapsed} toggle={() => setCollapsed(x => !x)} onNew={() => setView("home")} onSettings={() => setView("settings")} onSession={() => setView("session")}/>{view === "home" ? <Home onSend={() => setView("session")}/> : view === "settings" ? <Settings/> : <Workspace onSettings={() => setView("settings")}/>}<CommandPalette open={palette} close={() => setPalette(false)}/></div> }
